name: 月末処理のissue作成とプロジェクトへのリンク

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'ブランチ名'
        type: string

jobs:
  register_monthly_task:
    strategy:
      matrix:
        assignee: [member1, member2, member3]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || github.ref }}

      - uses: JasonEtco/create-an-issue@v2.9.2
        id: create_issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/monthly_task.md
          assignees: ${{ matrix.assignee }}